### ISSUE TITLE
node

### ISSUE THREAD

**Issue by giho8** [HasanAtilan/nodejs-layer7-stresserme#1]
Hi, when i run this comand 
node stresserme.js http://example.com 60

i have this error

SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by HasanAtilan** [comment]
You do not know how to run, I do not provide support from here I can help you if you post a topic on the forum !

https://stresser.me/
